apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kthena-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kthena-controller-manager
    {{- include "kthena.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ .Values.controllerManager.webhook.tls.certSecretName }}
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - model-booster-controller-config
    verbs:
      - get
