/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AutoscalingPolicyScaleUpPolicyApplyConfiguration represents a declarative configuration of the AutoscalingPolicyScaleUpPolicy type for use
// with apply.
//
// AutoscalingPolicyScaleUpPolicy defines the scaling up policy configuration.
type AutoscalingPolicyScaleUpPolicyApplyConfiguration struct {
	// StablePolicy defines the stable scaling policy that uses average metric values over time windows.
	// This policy smooths out short-term fluctuations and avoids unnecessary frequent scaling operations.
	StablePolicy *AutoscalingPolicyStablePolicyApplyConfiguration `json:"stablePolicy,omitempty"`
	// PanicPolicy defines the emergency scaling policy for handling sudden traffic spikes.
	// This policy activates during rapid load surges to prevent service degradation or timeouts.
	PanicPolicy *AutoscalingPolicyPanicPolicyApplyConfiguration `json:"panicPolicy,omitempty"`
}

// AutoscalingPolicyScaleUpPolicyApplyConfiguration constructs a declarative configuration of the AutoscalingPolicyScaleUpPolicy type for use with
// apply.
func AutoscalingPolicyScaleUpPolicy() *AutoscalingPolicyScaleUpPolicyApplyConfiguration {
	return &AutoscalingPolicyScaleUpPolicyApplyConfiguration{}
}

// WithStablePolicy sets the StablePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StablePolicy field is set to the value of the last call.
func (b *AutoscalingPolicyScaleUpPolicyApplyConfiguration) WithStablePolicy(value *AutoscalingPolicyStablePolicyApplyConfiguration) *AutoscalingPolicyScaleUpPolicyApplyConfiguration {
	b.StablePolicy = value
	return b
}

// WithPanicPolicy sets the PanicPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PanicPolicy field is set to the value of the last call.
func (b *AutoscalingPolicyScaleUpPolicyApplyConfiguration) WithPanicPolicy(value *AutoscalingPolicyPanicPolicyApplyConfiguration) *AutoscalingPolicyScaleUpPolicyApplyConfiguration {
	b.PanicPolicy = value
	return b
}
