/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// AutoscalingPolicyMetricApplyConfiguration represents a declarative configuration of the AutoscalingPolicyMetric type for use
// with apply.
type AutoscalingPolicyMetricApplyConfiguration struct {
	Name        *string            `json:"name,omitempty"`
	TargetValue *resource.Quantity `json:"targetValue,omitempty"`
}

// AutoscalingPolicyMetricApplyConfiguration constructs a declarative configuration of the AutoscalingPolicyMetric type for use with
// apply.
func AutoscalingPolicyMetric() *AutoscalingPolicyMetricApplyConfiguration {
	return &AutoscalingPolicyMetricApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AutoscalingPolicyMetricApplyConfiguration) WithName(value string) *AutoscalingPolicyMetricApplyConfiguration {
	b.Name = &value
	return b
}

// WithTargetValue sets the TargetValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetValue field is set to the value of the last call.
func (b *AutoscalingPolicyMetricApplyConfiguration) WithTargetValue(value resource.Quantity) *AutoscalingPolicyMetricApplyConfiguration {
	b.TargetValue = &value
	return b
}
