/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AutoscalingPolicyStatusApplyConfiguration represents a declarative configuration of the AutoscalingPolicyStatus type for use
// with apply.
type AutoscalingPolicyStatusApplyConfiguration struct {
	ObservedGeneration  *int64                                        `json:"observedGeneration,omitempty"`
	Conditions          []v1.ConditionApplyConfiguration              `json:"conditions,omitempty"`
	HomogeneousStatus   *TargetScalingStatusApplyConfiguration        `json:"homogeneousStatus,omitempty"`
	DisaggregatedStatus *DisaggregatedScalingStatusApplyConfiguration `json:"disaggregatedStatus,omitempty"`
	HeterogeneousStatus []TargetScalingStatusApplyConfiguration       `json:"heterogeneousStatus,omitempty"`
}

// AutoscalingPolicyStatusApplyConfiguration constructs a declarative configuration of the AutoscalingPolicyStatus type for use with
// apply.
func AutoscalingPolicyStatus() *AutoscalingPolicyStatusApplyConfiguration {
	return &AutoscalingPolicyStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *AutoscalingPolicyStatusApplyConfiguration) WithObservedGeneration(value int64) *AutoscalingPolicyStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *AutoscalingPolicyStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *AutoscalingPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithHomogeneousStatus sets the HomogeneousStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HomogeneousStatus field is set to the value of the last call.
func (b *AutoscalingPolicyStatusApplyConfiguration) WithHomogeneousStatus(value *TargetScalingStatusApplyConfiguration) *AutoscalingPolicyStatusApplyConfiguration {
	b.HomogeneousStatus = value
	return b
}

// WithDisaggregatedStatus sets the DisaggregatedStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisaggregatedStatus field is set to the value of the last call.
func (b *AutoscalingPolicyStatusApplyConfiguration) WithDisaggregatedStatus(value *DisaggregatedScalingStatusApplyConfiguration) *AutoscalingPolicyStatusApplyConfiguration {
	b.DisaggregatedStatus = value
	return b
}

// WithHeterogeneousStatus adds the given value to the HeterogeneousStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HeterogeneousStatus field.
func (b *AutoscalingPolicyStatusApplyConfiguration) WithHeterogeneousStatus(values ...*TargetScalingStatusApplyConfiguration) *AutoscalingPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeterogeneousStatus")
		}
		b.HeterogeneousStatus = append(b.HeterogeneousStatus, *values[i])
	}
	return b
}
