/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AutoscalingPolicySyncPolicyApplyConfiguration represents a declarative configuration of the AutoscalingPolicySyncPolicy type for use
// with apply.
type AutoscalingPolicySyncPolicyApplyConfiguration struct {
	DefaultPeriod   *v1.Duration `json:"defaultPeriod,omitempty"`
	ScaleUpPeriod   *v1.Duration `json:"scaleUpPeriod,omitempty"`
	ScaleDownPeriod *v1.Duration `json:"scaleDownPeriod,omitempty"`
}

// AutoscalingPolicySyncPolicyApplyConfiguration constructs a declarative configuration of the AutoscalingPolicySyncPolicy type for use with
// apply.
func AutoscalingPolicySyncPolicy() *AutoscalingPolicySyncPolicyApplyConfiguration {
	return &AutoscalingPolicySyncPolicyApplyConfiguration{}
}

// WithDefaultPeriod sets the DefaultPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultPeriod field is set to the value of the last call.
func (b *AutoscalingPolicySyncPolicyApplyConfiguration) WithDefaultPeriod(value v1.Duration) *AutoscalingPolicySyncPolicyApplyConfiguration {
	b.DefaultPeriod = &value
	return b
}

// WithScaleUpPeriod sets the ScaleUpPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScaleUpPeriod field is set to the value of the last call.
func (b *AutoscalingPolicySyncPolicyApplyConfiguration) WithScaleUpPeriod(value v1.Duration) *AutoscalingPolicySyncPolicyApplyConfiguration {
	b.ScaleUpPeriod = &value
	return b
}

// WithScaleDownPeriod sets the ScaleDownPeriod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScaleDownPeriod field is set to the value of the last call.
func (b *AutoscalingPolicySyncPolicyApplyConfiguration) WithScaleDownPeriod(value v1.Duration) *AutoscalingPolicySyncPolicyApplyConfiguration {
	b.ScaleDownPeriod = &value
	return b
}
