/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AutoscalingPolicySpecApplyConfiguration represents a declarative configuration of the AutoscalingPolicySpec type for use
// with apply.
//
// AutoscalingPolicySpec defines the desired state of AutoscalingPolicy.
//
// At most one of HomogeneousTarget, HeterogeneousTarget, or DisaggregatedTarget
// may be set. When the spec is used standalone (as an AutoscalingPolicy custom
// resource), exactly one target must be set; this is enforced by the
// autoscalingpolicy validating webhook rather than a CEL rule.
type AutoscalingPolicySpecApplyConfiguration struct {
	// TolerancePercent defines the percentage of deviation tolerated before scaling actions are triggered.
	// current_replicas represents the current number of instances, while target_replicas represents the expected number of instances calculated from monitoring metrics.
	// Scaling operations are performed only when |current_replicas - target_replicas| >= current_replicas * TolerancePercent / 100.
	TolerancePercent *int32 `json:"tolerancePercent,omitempty"`
	// Metrics defines the list of metrics used to evaluate scaling decisions.
	// This is the default metric list applied to scalable units. For
	// DisaggregatedTarget, role-level metrics override this list for that role.
	Metrics []AutoscalingPolicyMetricApplyConfiguration `json:"metrics,omitempty"`
	// Behavior defines the scaling behavior configuration for both scale up and scale down operations.
	Behavior *AutoscalingPolicyBehaviorApplyConfiguration `json:"behavior,omitempty"`
	// HomogeneousTarget enables traditional metric-based scaling for a single
	// ModelServing deployment (whole-deployment granularity).
	HomogeneousTarget *HomogeneousTargetApplyConfiguration `json:"homogeneousTarget,omitempty"`
	// HeterogeneousTarget enables optimization-based scaling across multiple
	// ModelServing deployments with different hardware capabilities.
	HeterogeneousTarget *HeterogeneousTargetApplyConfiguration `json:"heterogeneousTarget,omitempty"`
	// DisaggregatedTarget enables coordinated autoscaling of roles within a
	// single ModelServing that uses disaggregated serving.
	DisaggregatedTarget *DisaggregatedTargetApplyConfiguration `json:"disaggregatedTarget,omitempty"`
}

// AutoscalingPolicySpecApplyConfiguration constructs a declarative configuration of the AutoscalingPolicySpec type for use with
// apply.
func AutoscalingPolicySpec() *AutoscalingPolicySpecApplyConfiguration {
	return &AutoscalingPolicySpecApplyConfiguration{}
}

// WithTolerancePercent sets the TolerancePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TolerancePercent field is set to the value of the last call.
func (b *AutoscalingPolicySpecApplyConfiguration) WithTolerancePercent(value int32) *AutoscalingPolicySpecApplyConfiguration {
	b.TolerancePercent = &value
	return b
}

// WithMetrics adds the given value to the Metrics field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Metrics field.
func (b *AutoscalingPolicySpecApplyConfiguration) WithMetrics(values ...*AutoscalingPolicyMetricApplyConfiguration) *AutoscalingPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMetrics")
		}
		b.Metrics = append(b.Metrics, *values[i])
	}
	return b
}

// WithBehavior sets the Behavior field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Behavior field is set to the value of the last call.
func (b *AutoscalingPolicySpecApplyConfiguration) WithBehavior(value *AutoscalingPolicyBehaviorApplyConfiguration) *AutoscalingPolicySpecApplyConfiguration {
	b.Behavior = value
	return b
}

// WithHomogeneousTarget sets the HomogeneousTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HomogeneousTarget field is set to the value of the last call.
func (b *AutoscalingPolicySpecApplyConfiguration) WithHomogeneousTarget(value *HomogeneousTargetApplyConfiguration) *AutoscalingPolicySpecApplyConfiguration {
	b.HomogeneousTarget = value
	return b
}

// WithHeterogeneousTarget sets the HeterogeneousTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeterogeneousTarget field is set to the value of the last call.
func (b *AutoscalingPolicySpecApplyConfiguration) WithHeterogeneousTarget(value *HeterogeneousTargetApplyConfiguration) *AutoscalingPolicySpecApplyConfiguration {
	b.HeterogeneousTarget = value
	return b
}

// WithDisaggregatedTarget sets the DisaggregatedTarget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisaggregatedTarget field is set to the value of the last call.
func (b *AutoscalingPolicySpecApplyConfiguration) WithDisaggregatedTarget(value *DisaggregatedTargetApplyConfiguration) *AutoscalingPolicySpecApplyConfiguration {
	b.DisaggregatedTarget = value
	return b
}
