/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AutoscalingPolicyStablePolicyApplyConfiguration represents a declarative configuration of the AutoscalingPolicyStablePolicy type for use
// with apply.
//
// AutoscalingPolicyStablePolicy defines the stable scaling policy for both scale up and scale down operations.
type AutoscalingPolicyStablePolicyApplyConfiguration struct {
	// Instances defines the maximum absolute number of instances to scale per period.
	Instances *int32 `json:"instances,omitempty"`
	// Percent defines the maximum percentage of current instances to scale per period.
	Percent *int32 `json:"percent,omitempty"`
	// Period defines the time duration over which scaling metrics are evaluated.
	Period *v1.Duration `json:"period,omitempty"`
	// SelectPolicy determines the selection strategy for scaling operations.
	// 'Or' means scaling is performed if either the Percent or Instances requirement is met.
	// 'And' means scaling is performed only if both Percent and Instances requirements are met.
	SelectPolicy *workloadv1alpha1.SelectPolicyType `json:"selectPolicy,omitempty"`
	// StabilizationWindow defines the time window to stabilize scaling actions and prevent rapid oscillations.
	StabilizationWindow *v1.Duration `json:"stabilizationWindow,omitempty"`
}

// AutoscalingPolicyStablePolicyApplyConfiguration constructs a declarative configuration of the AutoscalingPolicyStablePolicy type for use with
// apply.
func AutoscalingPolicyStablePolicy() *AutoscalingPolicyStablePolicyApplyConfiguration {
	return &AutoscalingPolicyStablePolicyApplyConfiguration{}
}

// WithInstances sets the Instances field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instances field is set to the value of the last call.
func (b *AutoscalingPolicyStablePolicyApplyConfiguration) WithInstances(value int32) *AutoscalingPolicyStablePolicyApplyConfiguration {
	b.Instances = &value
	return b
}

// WithPercent sets the Percent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Percent field is set to the value of the last call.
func (b *AutoscalingPolicyStablePolicyApplyConfiguration) WithPercent(value int32) *AutoscalingPolicyStablePolicyApplyConfiguration {
	b.Percent = &value
	return b
}

// WithPeriod sets the Period field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Period field is set to the value of the last call.
func (b *AutoscalingPolicyStablePolicyApplyConfiguration) WithPeriod(value v1.Duration) *AutoscalingPolicyStablePolicyApplyConfiguration {
	b.Period = &value
	return b
}

// WithSelectPolicy sets the SelectPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelectPolicy field is set to the value of the last call.
func (b *AutoscalingPolicyStablePolicyApplyConfiguration) WithSelectPolicy(value workloadv1alpha1.SelectPolicyType) *AutoscalingPolicyStablePolicyApplyConfiguration {
	b.SelectPolicy = &value
	return b
}

// WithStabilizationWindow sets the StabilizationWindow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StabilizationWindow field is set to the value of the last call.
func (b *AutoscalingPolicyStablePolicyApplyConfiguration) WithStabilizationWindow(value v1.Duration) *AutoscalingPolicyStablePolicyApplyConfiguration {
	b.StabilizationWindow = &value
	return b
}
