/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// DisaggregatedTargetApplyConfiguration represents a declarative configuration of the DisaggregatedTarget type for use
// with apply.
type DisaggregatedTargetApplyConfiguration struct {
	TargetRef       *v1.ObjectReference                           `json:"targetRef,omitempty"`
	Roles           map[string]RoleScalingParamApplyConfiguration `json:"roles,omitempty"`
	RatioConstraint *RoleRatioConstraintApplyConfiguration        `json:"ratioConstraint,omitempty"`
}

// DisaggregatedTargetApplyConfiguration constructs a declarative configuration of the DisaggregatedTarget type for use with
// apply.
func DisaggregatedTarget() *DisaggregatedTargetApplyConfiguration {
	return &DisaggregatedTargetApplyConfiguration{}
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *DisaggregatedTargetApplyConfiguration) WithTargetRef(value v1.ObjectReference) *DisaggregatedTargetApplyConfiguration {
	b.TargetRef = &value
	return b
}

// WithRoles puts the entries into the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Roles field,
// overwriting an existing map entries in Roles field with the same key.
func (b *DisaggregatedTargetApplyConfiguration) WithRoles(entries map[string]RoleScalingParamApplyConfiguration) *DisaggregatedTargetApplyConfiguration {
	if b.Roles == nil && len(entries) > 0 {
		b.Roles = make(map[string]RoleScalingParamApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Roles[k] = v
	}
	return b
}

// WithRatioConstraint sets the RatioConstraint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RatioConstraint field is set to the value of the last call.
func (b *DisaggregatedTargetApplyConfiguration) WithRatioConstraint(value *RoleRatioConstraintApplyConfiguration) *DisaggregatedTargetApplyConfiguration {
	b.RatioConstraint = value
	return b
}
