/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
)

// EvictionStrategyApplyConfiguration represents a declarative configuration of the EvictionStrategy type for use
// with apply.
type EvictionStrategyApplyConfiguration struct {
	Level            *workloadv1alpha1.EvictionProtectionLevel `json:"level,omitempty"`
	MinAvailable     *int32                                    `json:"minAvailable,omitempty"`
	RoleMinAvailable map[string]int32                          `json:"roleMinAvailable,omitempty"`
}

// EvictionStrategyApplyConfiguration constructs a declarative configuration of the EvictionStrategy type for use with
// apply.
func EvictionStrategy() *EvictionStrategyApplyConfiguration {
	return &EvictionStrategyApplyConfiguration{}
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *EvictionStrategyApplyConfiguration) WithLevel(value workloadv1alpha1.EvictionProtectionLevel) *EvictionStrategyApplyConfiguration {
	b.Level = &value
	return b
}

// WithMinAvailable sets the MinAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAvailable field is set to the value of the last call.
func (b *EvictionStrategyApplyConfiguration) WithMinAvailable(value int32) *EvictionStrategyApplyConfiguration {
	b.MinAvailable = &value
	return b
}

// WithRoleMinAvailable puts the entries into the RoleMinAvailable field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RoleMinAvailable field,
// overwriting an existing map entries in RoleMinAvailable field with the same key.
func (b *EvictionStrategyApplyConfiguration) WithRoleMinAvailable(entries map[string]int32) *EvictionStrategyApplyConfiguration {
	if b.RoleMinAvailable == nil && len(entries) > 0 {
		b.RoleMinAvailable = make(map[string]int32, len(entries))
	}
	for k, v := range entries {
		b.RoleMinAvailable[k] = v
	}
	return b
}
