/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// EvictionStrategySpecApplyConfiguration represents a declarative configuration of the EvictionStrategySpec type for use
// with apply.
type EvictionStrategySpecApplyConfiguration struct {
	ProtectionLevel  *workloadv1alpha1.ProtectionLevelType `json:"protectionLevel,omitempty"`
	MinAvailable     *intstr.IntOrString                   `json:"minAvailable,omitempty"`
	RoleMinAvailable map[string]intstr.IntOrString         `json:"roleMinAvailable,omitempty"`
}

// EvictionStrategySpecApplyConfiguration constructs a declarative configuration of the EvictionStrategySpec type for use with
// apply.
func EvictionStrategySpec() *EvictionStrategySpecApplyConfiguration {
	return &EvictionStrategySpecApplyConfiguration{}
}

// WithProtectionLevel sets the ProtectionLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtectionLevel field is set to the value of the last call.
func (b *EvictionStrategySpecApplyConfiguration) WithProtectionLevel(value workloadv1alpha1.ProtectionLevelType) *EvictionStrategySpecApplyConfiguration {
	b.ProtectionLevel = &value
	return b
}

// WithMinAvailable sets the MinAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAvailable field is set to the value of the last call.
func (b *EvictionStrategySpecApplyConfiguration) WithMinAvailable(value intstr.IntOrString) *EvictionStrategySpecApplyConfiguration {
	b.MinAvailable = &value
	return b
}

// WithRoleMinAvailable puts the entries into the RoleMinAvailable field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RoleMinAvailable field,
// overwriting an existing map entries in RoleMinAvailable field with the same key.
func (b *EvictionStrategySpecApplyConfiguration) WithRoleMinAvailable(entries map[string]intstr.IntOrString) *EvictionStrategySpecApplyConfiguration {
	if b.RoleMinAvailable == nil && len(entries) > 0 {
		b.RoleMinAvailable = make(map[string]intstr.IntOrString, len(entries))
	}
	for k, v := range entries {
		b.RoleMinAvailable[k] = v
	}
	return b
}
