/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GangPolicyApplyConfiguration represents a declarative configuration of the GangPolicy type for use
// with apply.
//
// GangPolicy defines the gang scheduling configuration.
type GangPolicyApplyConfiguration struct {
	// MinRoleReplicas defines the minimum number of replicas required for each role
	// in gang scheduling, pods in each role are strictly gang required.
	// This map allows users to specify different minimum replica requirements for different roles.
	// If this field is not set, all roles in the ServingGroup are considered gang required by default.
	// For example if you specify a 2P(prefill) 4D(decode) serving group and set the below gangPolicy:
	// ```yaml
	// gangPolicy:
	// minRoleReplicas:
	// prefill: 1
	// decode: 1
	// ```
	// It will result in the following behavior:
	// At least one prefill and one decode must be scheduled before any of the pods in the serving group can run.
	// And pods within a role must be scheduled together.
	MinRoleReplicas map[string]int32 `json:"minRoleReplicas,omitempty"`
}

// GangPolicyApplyConfiguration constructs a declarative configuration of the GangPolicy type for use with
// apply.
func GangPolicy() *GangPolicyApplyConfiguration {
	return &GangPolicyApplyConfiguration{}
}

// WithMinRoleReplicas puts the entries into the MinRoleReplicas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MinRoleReplicas field,
// overwriting an existing map entries in MinRoleReplicas field with the same key.
func (b *GangPolicyApplyConfiguration) WithMinRoleReplicas(entries map[string]int32) *GangPolicyApplyConfiguration {
	if b.MinRoleReplicas == nil && len(entries) > 0 {
		b.MinRoleReplicas = make(map[string]int32, len(entries))
	}
	for k, v := range entries {
		b.MinRoleReplicas[k] = v
	}
	return b
}
