/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeterogeneousTargetParamApplyConfiguration represents a declarative configuration of the HeterogeneousTargetParam type for use
// with apply.
//
// HeterogeneousTargetParam defines the configuration parameters for a specific deployment type in heterogeneous scaling.
//
// Example (one expensive H100 group within a HeterogeneousTarget):
//
// cost: 100
// minReplicas: 0
// maxReplicas: 4
// target:
// targetRef:
// kind: ModelServing
// name: llama-h100
type HeterogeneousTargetParamApplyConfiguration struct {
	// Target defines the scaling instance configuration for this deployment type.
	Target *TargetApplyConfiguration `json:"target,omitempty"`
	// Cost defines the relative cost factor used in optimization calculations.
	// This factor balances performance requirements against deployment costs.
	// Values are relative across params, e.g. 100 for an H100 group and 60 for a
	// cheaper A100 group makes the optimizer prefer A100 replicas when adequate.
	Cost *int32 `json:"cost,omitempty"`
	// MinReplicas defines the minimum number of replicas to maintain for this deployment type.
	MinReplicas *int32 `json:"minReplicas,omitempty"`
	// MaxReplicas defines the maximum number of replicas allowed for this deployment type.
	MaxReplicas *int32 `json:"maxReplicas,omitempty"`
}

// HeterogeneousTargetParamApplyConfiguration constructs a declarative configuration of the HeterogeneousTargetParam type for use with
// apply.
func HeterogeneousTargetParam() *HeterogeneousTargetParamApplyConfiguration {
	return &HeterogeneousTargetParamApplyConfiguration{}
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *HeterogeneousTargetParamApplyConfiguration) WithTarget(value *TargetApplyConfiguration) *HeterogeneousTargetParamApplyConfiguration {
	b.Target = value
	return b
}

// WithCost sets the Cost field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cost field is set to the value of the last call.
func (b *HeterogeneousTargetParamApplyConfiguration) WithCost(value int32) *HeterogeneousTargetParamApplyConfiguration {
	b.Cost = &value
	return b
}

// WithMinReplicas sets the MinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicas field is set to the value of the last call.
func (b *HeterogeneousTargetParamApplyConfiguration) WithMinReplicas(value int32) *HeterogeneousTargetParamApplyConfiguration {
	b.MinReplicas = &value
	return b
}

// WithMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReplicas field is set to the value of the last call.
func (b *HeterogeneousTargetParamApplyConfiguration) WithMaxReplicas(value int32) *HeterogeneousTargetParamApplyConfiguration {
	b.MaxReplicas = &value
	return b
}
