/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeterogeneousTargetApplyConfiguration represents a declarative configuration of the HeterogeneousTarget type for use
// with apply.
//
// HeterogeneousTarget defines the configuration for optimization-based autoscaling across multiple deployments.
//
// It distributes replicas across several ModelServing groups with different
// hardware (and therefore different Cost) to satisfy the overall demand at the
// lowest cost. Each group is described by one entry in Params.
//
// Example (split capacity between an H100 group and a cheaper A100 group):
//
// heterogeneousTarget:
// costExpansionRatePercent: 200
// params:
// - cost: 100
// minReplicas: 0
// maxReplicas: 4
// target:
// targetRef:
// kind: ModelServing
// name: llama-h100
// - cost: 60
// minReplicas: 1
// maxReplicas: 8
// target:
// targetRef:
// kind: ModelServing
// name: llama-a100
type HeterogeneousTargetApplyConfiguration struct {
	// Params defines the configuration parameters for multiple ModelServing groups to be optimized.
	Params []HeterogeneousTargetParamApplyConfiguration `json:"params,omitempty"`
	// CostExpansionRatePercent defines the percentage rate at which the cost expands during optimization calculations.
	// For example, 200 allows the optimizer to spend up to 2x the minimal cost to
	// meet performance targets before refusing to scale further.
	CostExpansionRatePercent *int32 `json:"costExpansionRatePercent,omitempty"`
}

// HeterogeneousTargetApplyConfiguration constructs a declarative configuration of the HeterogeneousTarget type for use with
// apply.
func HeterogeneousTarget() *HeterogeneousTargetApplyConfiguration {
	return &HeterogeneousTargetApplyConfiguration{}
}

// WithParams adds the given value to the Params field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Params field.
func (b *HeterogeneousTargetApplyConfiguration) WithParams(values ...*HeterogeneousTargetParamApplyConfiguration) *HeterogeneousTargetApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParams")
		}
		b.Params = append(b.Params, *values[i])
	}
	return b
}

// WithCostExpansionRatePercent sets the CostExpansionRatePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CostExpansionRatePercent field is set to the value of the last call.
func (b *HeterogeneousTargetApplyConfiguration) WithCostExpansionRatePercent(value int32) *HeterogeneousTargetApplyConfiguration {
	b.CostExpansionRatePercent = &value
	return b
}
