/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HomogeneousTargetApplyConfiguration represents a declarative configuration of the HomogeneousTarget type for use
// with apply.
//
// HomogeneousTarget defines the configuration for traditional metric-based autoscaling of a single deployment.
//
// Example (scale podinfo-ms between 1 and 6 replicas based on RPS):
//
// homogeneousTarget:
// minReplicas: 1
// maxReplicas: 6
// target:
// targetRef:
// kind: ModelServing
// name: podinfo-ms
// metricSources:
// podinfo_rps:
// prometheus:
// serverURL: http://prometheus.monitoring.svc:9090
// query: sum(rate(http_requests_total[2m]))
type HomogeneousTargetApplyConfiguration struct {
	// Target defines the object to be monitored and scaled.
	Target *TargetApplyConfiguration `json:"target,omitempty"`
	// MinReplicas defines the minimum number of replicas to maintain (e.g., 1).
	MinReplicas *int32 `json:"minReplicas,omitempty"`
	// MaxReplicas defines the maximum number of replicas allowed (e.g., 6).
	MaxReplicas *int32 `json:"maxReplicas,omitempty"`
}

// HomogeneousTargetApplyConfiguration constructs a declarative configuration of the HomogeneousTarget type for use with
// apply.
func HomogeneousTarget() *HomogeneousTargetApplyConfiguration {
	return &HomogeneousTargetApplyConfiguration{}
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *HomogeneousTargetApplyConfiguration) WithTarget(value *TargetApplyConfiguration) *HomogeneousTargetApplyConfiguration {
	b.Target = value
	return b
}

// WithMinReplicas sets the MinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicas field is set to the value of the last call.
func (b *HomogeneousTargetApplyConfiguration) WithMinReplicas(value int32) *HomogeneousTargetApplyConfiguration {
	b.MinReplicas = &value
	return b
}

// WithMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReplicas field is set to the value of the last call.
func (b *HomogeneousTargetApplyConfiguration) WithMaxReplicas(value int32) *HomogeneousTargetApplyConfiguration {
	b.MaxReplicas = &value
	return b
}
