/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MetricSourceApplyConfiguration represents a declarative configuration of the MetricSource type for use
// with apply.
type MetricSourceApplyConfiguration struct {
	Pod        *PodMetricSourceApplyConfiguration        `json:"pod,omitempty"`
	Prometheus *PrometheusMetricSourceApplyConfiguration `json:"prometheus,omitempty"`
}

// MetricSourceApplyConfiguration constructs a declarative configuration of the MetricSource type for use with
// apply.
func MetricSource() *MetricSourceApplyConfiguration {
	return &MetricSourceApplyConfiguration{}
}

// WithPod sets the Pod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pod field is set to the value of the last call.
func (b *MetricSourceApplyConfiguration) WithPod(value *PodMetricSourceApplyConfiguration) *MetricSourceApplyConfiguration {
	b.Pod = value
	return b
}

// WithPrometheus sets the Prometheus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prometheus field is set to the value of the last call.
func (b *MetricSourceApplyConfiguration) WithPrometheus(value *PrometheusMetricSourceApplyConfiguration) *MetricSourceApplyConfiguration {
	b.Prometheus = value
	return b
}
