/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ModelServingRoleReplicaSpecApplyConfiguration represents a declarative configuration of the ModelServingRoleReplicaSpec type for use
// with apply.
type ModelServingRoleReplicaSpecApplyConfiguration struct {
	ModelServingRef *v1.LocalObjectReference `json:"modelServingRef,omitempty"`
	RoleName        *string                  `json:"roleName,omitempty"`
	Replicas        *int32                   `json:"replicas,omitempty"`
}

// ModelServingRoleReplicaSpecApplyConfiguration constructs a declarative configuration of the ModelServingRoleReplicaSpec type for use with
// apply.
func ModelServingRoleReplicaSpec() *ModelServingRoleReplicaSpecApplyConfiguration {
	return &ModelServingRoleReplicaSpecApplyConfiguration{}
}

// WithModelServingRef sets the ModelServingRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelServingRef field is set to the value of the last call.
func (b *ModelServingRoleReplicaSpecApplyConfiguration) WithModelServingRef(value v1.LocalObjectReference) *ModelServingRoleReplicaSpecApplyConfiguration {
	b.ModelServingRef = &value
	return b
}

// WithRoleName sets the RoleName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleName field is set to the value of the last call.
func (b *ModelServingRoleReplicaSpecApplyConfiguration) WithRoleName(value string) *ModelServingRoleReplicaSpecApplyConfiguration {
	b.RoleName = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ModelServingRoleReplicaSpecApplyConfiguration) WithReplicas(value int32) *ModelServingRoleReplicaSpecApplyConfiguration {
	b.Replicas = &value
	return b
}
