/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ModelServingStatusApplyConfiguration represents a declarative configuration of the ModelServingStatus type for use
// with apply.
type ModelServingStatusApplyConfiguration struct {
	ObservedGeneration *int64                           `json:"observedGeneration,omitempty"`
	Replicas           *int32                           `json:"replicas,omitempty"`
	CurrentReplicas    *int32                           `json:"currentReplicas,omitempty"`
	UpdatedReplicas    *int32                           `json:"updatedReplicas,omitempty"`
	AvailableReplicas  *int32                           `json:"availableReplicas,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	LabelSelector      *string                          `json:"labelSelector,omitempty"`
}

// ModelServingStatusApplyConfiguration constructs a declarative configuration of the ModelServingStatus type for use with
// apply.
func ModelServingStatus() *ModelServingStatusApplyConfiguration {
	return &ModelServingStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ModelServingStatusApplyConfiguration) WithObservedGeneration(value int64) *ModelServingStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ModelServingStatusApplyConfiguration) WithReplicas(value int32) *ModelServingStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithCurrentReplicas sets the CurrentReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentReplicas field is set to the value of the last call.
func (b *ModelServingStatusApplyConfiguration) WithCurrentReplicas(value int32) *ModelServingStatusApplyConfiguration {
	b.CurrentReplicas = &value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *ModelServingStatusApplyConfiguration) WithUpdatedReplicas(value int32) *ModelServingStatusApplyConfiguration {
	b.UpdatedReplicas = &value
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *ModelServingStatusApplyConfiguration) WithAvailableReplicas(value int32) *ModelServingStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ModelServingStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ModelServingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *ModelServingStatusApplyConfiguration) WithLabelSelector(value string) *ModelServingStatusApplyConfiguration {
	b.LabelSelector = &value
	return b
}
