/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// PDDisaggregatedTargetApplyConfiguration represents a declarative configuration of the PDDisaggregatedTarget type for use
// with apply.
type PDDisaggregatedTargetApplyConfiguration struct {
	ModelServingRef    *v1.LocalObjectReference        `json:"modelServingRef,omitempty"`
	PrefillRole        *PDRoleTargetApplyConfiguration `json:"prefillRole,omitempty"`
	DecodeRole         *PDRoleTargetApplyConfiguration `json:"decodeRole,omitempty"`
	PrefillDecodeRatio *string                         `json:"prefillDecodeRatio,omitempty"`
}

// PDDisaggregatedTargetApplyConfiguration constructs a declarative configuration of the PDDisaggregatedTarget type for use with
// apply.
func PDDisaggregatedTarget() *PDDisaggregatedTargetApplyConfiguration {
	return &PDDisaggregatedTargetApplyConfiguration{}
}

// WithModelServingRef sets the ModelServingRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelServingRef field is set to the value of the last call.
func (b *PDDisaggregatedTargetApplyConfiguration) WithModelServingRef(value v1.LocalObjectReference) *PDDisaggregatedTargetApplyConfiguration {
	b.ModelServingRef = &value
	return b
}

// WithPrefillRole sets the PrefillRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefillRole field is set to the value of the last call.
func (b *PDDisaggregatedTargetApplyConfiguration) WithPrefillRole(value *PDRoleTargetApplyConfiguration) *PDDisaggregatedTargetApplyConfiguration {
	b.PrefillRole = value
	return b
}

// WithDecodeRole sets the DecodeRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DecodeRole field is set to the value of the last call.
func (b *PDDisaggregatedTargetApplyConfiguration) WithDecodeRole(value *PDRoleTargetApplyConfiguration) *PDDisaggregatedTargetApplyConfiguration {
	b.DecodeRole = value
	return b
}

// WithPrefillDecodeRatio sets the PrefillDecodeRatio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefillDecodeRatio field is set to the value of the last call.
func (b *PDDisaggregatedTargetApplyConfiguration) WithPrefillDecodeRatio(value string) *PDDisaggregatedTargetApplyConfiguration {
	b.PrefillDecodeRatio = &value
	return b
}
