/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PDScalingStatusApplyConfiguration represents a declarative configuration of the PDScalingStatus type for use
// with apply.
type PDScalingStatusApplyConfiguration struct {
	PrefillReplicas *int32   `json:"prefillReplicas,omitempty"`
	DecodeReplicas  *int32   `json:"decodeReplicas,omitempty"`
	EffectiveRatio  *string  `json:"effectiveRatio,omitempty"`
	LastScaleTime   *v1.Time `json:"lastScaleTime,omitempty"`
}

// PDScalingStatusApplyConfiguration constructs a declarative configuration of the PDScalingStatus type for use with
// apply.
func PDScalingStatus() *PDScalingStatusApplyConfiguration {
	return &PDScalingStatusApplyConfiguration{}
}

// WithPrefillReplicas sets the PrefillReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefillReplicas field is set to the value of the last call.
func (b *PDScalingStatusApplyConfiguration) WithPrefillReplicas(value int32) *PDScalingStatusApplyConfiguration {
	b.PrefillReplicas = &value
	return b
}

// WithDecodeReplicas sets the DecodeReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DecodeReplicas field is set to the value of the last call.
func (b *PDScalingStatusApplyConfiguration) WithDecodeReplicas(value int32) *PDScalingStatusApplyConfiguration {
	b.DecodeReplicas = &value
	return b
}

// WithEffectiveRatio sets the EffectiveRatio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveRatio field is set to the value of the last call.
func (b *PDScalingStatusApplyConfiguration) WithEffectiveRatio(value string) *PDScalingStatusApplyConfiguration {
	b.EffectiveRatio = &value
	return b
}

// WithLastScaleTime sets the LastScaleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScaleTime field is set to the value of the last call.
func (b *PDScalingStatusApplyConfiguration) WithLastScaleTime(value v1.Time) *PDScalingStatusApplyConfiguration {
	b.LastScaleTime = &value
	return b
}
