/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
)

// PluginScopeApplyConfiguration represents a declarative configuration of the PluginScope type for use
// with apply.
//
// PluginScope restricts where a plugin is applied.
// Roles is a whitelist; empty means all roles.
// Target limits to entry/worker/all pods; empty means all pods.
type PluginScopeApplyConfiguration struct {
	// Roles limits the plugin to the specified role names.
	Roles []string `json:"roles,omitempty"`
	// Target limits the plugin to specific pod target (Entry/Worker/All).
	// kubebuilder:default=All
	// kubebuilder:validation:Enum={All,Entry,Worker}
	Target *workloadv1alpha1.PluginTarget `json:"target,omitempty"`
}

// PluginScopeApplyConfiguration constructs a declarative configuration of the PluginScope type for use with
// apply.
func PluginScope() *PluginScopeApplyConfiguration {
	return &PluginScopeApplyConfiguration{}
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *PluginScopeApplyConfiguration) WithRoles(values ...string) *PluginScopeApplyConfiguration {
	for i := range values {
		b.Roles = append(b.Roles, values[i])
	}
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *PluginScopeApplyConfiguration) WithTarget(value workloadv1alpha1.PluginTarget) *PluginScopeApplyConfiguration {
	b.Target = &value
	return b
}
