/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// PluginSpecApplyConfiguration represents a declarative configuration of the PluginSpec type for use
// with apply.
type PluginSpecApplyConfiguration struct {
	Name   *string                        `json:"name,omitempty"`
	Type   *workloadv1alpha1.PluginType   `json:"type,omitempty"`
	Config *v1.JSON                       `json:"config,omitempty"`
	Scope  *PluginScopeApplyConfiguration `json:"scope,omitempty"`
}

// PluginSpecApplyConfiguration constructs a declarative configuration of the PluginSpec type for use with
// apply.
func PluginSpec() *PluginSpecApplyConfiguration {
	return &PluginSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PluginSpecApplyConfiguration) WithName(value string) *PluginSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *PluginSpecApplyConfiguration) WithType(value workloadv1alpha1.PluginType) *PluginSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *PluginSpecApplyConfiguration) WithConfig(value v1.JSON) *PluginSpecApplyConfiguration {
	b.Config = &value
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *PluginSpecApplyConfiguration) WithScope(value *PluginScopeApplyConfiguration) *PluginSpecApplyConfiguration {
	b.Scope = value
	return b
}
