/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodMetricSourceApplyConfiguration represents a declarative configuration of the PodMetricSource type for use
// with apply.
//
// PodMetricSource configures pod-endpoint scraping for a metric.
//
// For each matching Pod, metrics are scraped from the constructed access link and extracted from Prometheus’s text output
// for the metric family identified by Name.
//
// Example (each pod exposes "vllm:num_requests_waiting" on its named "metrics" port):
//
// pod:
// name: vllm:num_requests_waiting
// uri: /metrics
// portName: metrics
// labelSelector:
// matchLabels:
// role: decode
//
// The resulting scrape URL uses the container port named "metrics" from each selected Pod.
type PodMetricSourceApplyConfiguration struct {
	// Name is the Prometheus metric name matched against labels in the pod's scraped output.
	// Defaults to the policy metric key when omitted.
	// For example, set it to "vllm:gpu_cache_usage_perc" to read that exact series.
	Name *string `json:"name,omitempty"`
	// Uri defines the HTTP path where metrics are exposed (e.g., "/metrics").
	Uri *string `json:"uri,omitempty"`
	// Port defines the network port where metrics are exposed by the pods (e.g., 8000).
	// When both port and portName are omitted, the runtime uses port 8100.
	Port *int32 `json:"port,omitempty"`
	// PortName selects a named TCP container port from each matching Pod.
	// Pods may use different numbers for the same name.
	PortName *string `json:"portName,omitempty"`
	// LabelSelector defines additional filtering for pods exposing this metric.
	// Only pods matching both the target and this selector are scraped, e.g.
	// matchLabels with role=decode to scrape only the decode role's pods.
	LabelSelector *v1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
}

// PodMetricSourceApplyConfiguration constructs a declarative configuration of the PodMetricSource type for use with
// apply.
func PodMetricSource() *PodMetricSourceApplyConfiguration {
	return &PodMetricSourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodMetricSourceApplyConfiguration) WithName(value string) *PodMetricSourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithUri sets the Uri field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uri field is set to the value of the last call.
func (b *PodMetricSourceApplyConfiguration) WithUri(value string) *PodMetricSourceApplyConfiguration {
	b.Uri = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *PodMetricSourceApplyConfiguration) WithPort(value int32) *PodMetricSourceApplyConfiguration {
	b.Port = &value
	return b
}

// WithPortName sets the PortName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortName field is set to the value of the last call.
func (b *PodMetricSourceApplyConfiguration) WithPortName(value string) *PodMetricSourceApplyConfiguration {
	b.PortName = &value
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *PodMetricSourceApplyConfiguration) WithLabelSelector(value *v1.LabelSelectorApplyConfiguration) *PodMetricSourceApplyConfiguration {
	b.LabelSelector = value
	return b
}
