/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// PodTemplateSpecApplyConfiguration represents a declarative configuration of the PodTemplateSpec type for use
// with apply.
//
// PodTemplateSpec describes the data a pod should have when created from a template
type PodTemplateSpecApplyConfiguration struct {
	// Object's metadata.
	Metadata *MetadataApplyConfiguration `json:"metadata,omitempty"`
	// Specification of the desired behavior of the pod.
	Spec *v1.PodSpec `json:"spec,omitempty"`
}

// PodTemplateSpecApplyConfiguration constructs a declarative configuration of the PodTemplateSpec type for use with
// apply.
func PodTemplateSpec() *PodTemplateSpecApplyConfiguration {
	return &PodTemplateSpecApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *PodTemplateSpecApplyConfiguration) WithMetadata(value *MetadataApplyConfiguration) *PodTemplateSpecApplyConfiguration {
	b.Metadata = value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *PodTemplateSpecApplyConfiguration) WithSpec(value v1.PodSpec) *PodTemplateSpecApplyConfiguration {
	b.Spec = &value
	return b
}
