/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
)

// PrometheusMetricSourceApplyConfiguration represents a declarative configuration of the PrometheusMetricSource type for use
// with apply.
type PrometheusMetricSourceApplyConfiguration struct {
	ServerURL *string                          `json:"serverURL,omitempty"`
	Query     *string                          `json:"query,omitempty"`
	Auth      *workloadv1alpha1.PrometheusAuth `json:"auth,omitempty"`
}

// PrometheusMetricSourceApplyConfiguration constructs a declarative configuration of the PrometheusMetricSource type for use with
// apply.
func PrometheusMetricSource() *PrometheusMetricSourceApplyConfiguration {
	return &PrometheusMetricSourceApplyConfiguration{}
}

// WithServerURL sets the ServerURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerURL field is set to the value of the last call.
func (b *PrometheusMetricSourceApplyConfiguration) WithServerURL(value string) *PrometheusMetricSourceApplyConfiguration {
	b.ServerURL = &value
	return b
}

// WithQuery sets the Query field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Query field is set to the value of the last call.
func (b *PrometheusMetricSourceApplyConfiguration) WithQuery(value string) *PrometheusMetricSourceApplyConfiguration {
	b.Query = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *PrometheusMetricSourceApplyConfiguration) WithAuth(value workloadv1alpha1.PrometheusAuth) *PrometheusMetricSourceApplyConfiguration {
	b.Auth = &value
	return b
}
