/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RevisionInfoApplyConfiguration represents a declarative configuration of the RevisionInfo type for use
// with apply.
type RevisionInfoApplyConfiguration struct {
	Revision       *string `json:"revision,omitempty"`
	Count          *int32  `json:"count,omitempty"`
	ServingGroups  []int32 `json:"servingGroups,omitempty"`
	AvailableCount *int32  `json:"availableCount,omitempty"`
}

// RevisionInfoApplyConfiguration constructs a declarative configuration of the RevisionInfo type for use with
// apply.
func RevisionInfo() *RevisionInfoApplyConfiguration {
	return &RevisionInfoApplyConfiguration{}
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *RevisionInfoApplyConfiguration) WithRevision(value string) *RevisionInfoApplyConfiguration {
	b.Revision = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *RevisionInfoApplyConfiguration) WithCount(value int32) *RevisionInfoApplyConfiguration {
	b.Count = &value
	return b
}

// WithServingGroups adds the given value to the ServingGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServingGroups field.
func (b *RevisionInfoApplyConfiguration) WithServingGroups(values ...int32) *RevisionInfoApplyConfiguration {
	for i := range values {
		b.ServingGroups = append(b.ServingGroups, values[i])
	}
	return b
}

// WithAvailableCount sets the AvailableCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableCount field is set to the value of the last call.
func (b *RevisionInfoApplyConfiguration) WithAvailableCount(value int32) *RevisionInfoApplyConfiguration {
	b.AvailableCount = &value
	return b
}
