/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleRatioStatusApplyConfiguration represents a declarative configuration of the RoleRatioStatus type for use
// with apply.
type RoleRatioStatusApplyConfiguration struct {
	NumeratorRole   *string `json:"numeratorRole,omitempty"`
	DenominatorRole *string `json:"denominatorRole,omitempty"`
	CurrentRatio    *string `json:"currentRatio,omitempty"`
}

// RoleRatioStatusApplyConfiguration constructs a declarative configuration of the RoleRatioStatus type for use with
// apply.
func RoleRatioStatus() *RoleRatioStatusApplyConfiguration {
	return &RoleRatioStatusApplyConfiguration{}
}

// WithNumeratorRole sets the NumeratorRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NumeratorRole field is set to the value of the last call.
func (b *RoleRatioStatusApplyConfiguration) WithNumeratorRole(value string) *RoleRatioStatusApplyConfiguration {
	b.NumeratorRole = &value
	return b
}

// WithDenominatorRole sets the DenominatorRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DenominatorRole field is set to the value of the last call.
func (b *RoleRatioStatusApplyConfiguration) WithDenominatorRole(value string) *RoleRatioStatusApplyConfiguration {
	b.DenominatorRole = &value
	return b
}

// WithCurrentRatio sets the CurrentRatio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentRatio field is set to the value of the last call.
func (b *RoleRatioStatusApplyConfiguration) WithCurrentRatio(value string) *RoleRatioStatusApplyConfiguration {
	b.CurrentRatio = &value
	return b
}
