/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleScalingParamApplyConfiguration represents a declarative configuration of the RoleScalingParam type for use
// with apply.
type RoleScalingParamApplyConfiguration struct {
	MinReplicas   *int32                                      `json:"minReplicas,omitempty"`
	MaxReplicas   *int32                                      `json:"maxReplicas,omitempty"`
	Metrics       []AutoscalingPolicyMetricApplyConfiguration `json:"metrics,omitempty"`
	MetricSources map[string]MetricSourceApplyConfiguration   `json:"metricSources,omitempty"`
}

// RoleScalingParamApplyConfiguration constructs a declarative configuration of the RoleScalingParam type for use with
// apply.
func RoleScalingParam() *RoleScalingParamApplyConfiguration {
	return &RoleScalingParamApplyConfiguration{}
}

// WithMinReplicas sets the MinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicas field is set to the value of the last call.
func (b *RoleScalingParamApplyConfiguration) WithMinReplicas(value int32) *RoleScalingParamApplyConfiguration {
	b.MinReplicas = &value
	return b
}

// WithMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReplicas field is set to the value of the last call.
func (b *RoleScalingParamApplyConfiguration) WithMaxReplicas(value int32) *RoleScalingParamApplyConfiguration {
	b.MaxReplicas = &value
	return b
}

// WithMetrics adds the given value to the Metrics field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Metrics field.
func (b *RoleScalingParamApplyConfiguration) WithMetrics(values ...*AutoscalingPolicyMetricApplyConfiguration) *RoleScalingParamApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMetrics")
		}
		b.Metrics = append(b.Metrics, *values[i])
	}
	return b
}

// WithMetricSources puts the entries into the MetricSources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MetricSources field,
// overwriting an existing map entries in MetricSources field with the same key.
func (b *RoleScalingParamApplyConfiguration) WithMetricSources(entries map[string]MetricSourceApplyConfiguration) *RoleScalingParamApplyConfiguration {
	if b.MetricSources == nil && len(entries) > 0 {
		b.MetricSources = make(map[string]MetricSourceApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.MetricSources[k] = v
	}
	return b
}
