/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleRolloutDependencyApplyConfiguration represents a declarative configuration of the RoleRolloutDependency type for use
// with apply.
type RoleRolloutDependencyApplyConfiguration struct {
	Role      *string  `json:"role,omitempty"`
	DependsOn []string `json:"dependsOn,omitempty"`
}

// RoleRolloutDependencyApplyConfiguration constructs a declarative configuration of the RoleRolloutDependency type for use with
// apply.
func RoleRolloutDependency() *RoleRolloutDependencyApplyConfiguration {
	return &RoleRolloutDependencyApplyConfiguration{}
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *RoleRolloutDependencyApplyConfiguration) WithRole(value string) *RoleRolloutDependencyApplyConfiguration {
	b.Role = &value
	return b
}

// WithDependsOn adds the given value to the DependsOn field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DependsOn field.
func (b *RoleRolloutDependencyApplyConfiguration) WithDependsOn(values ...string) *RoleRolloutDependencyApplyConfiguration {
	for i := range values {
		b.DependsOn = append(b.DependsOn, values[i])
	}
	return b
}
