/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// RollingUpdateConfigurationApplyConfiguration represents a declarative configuration of the RollingUpdateConfiguration type for use
// with apply.
//
// RollingUpdateConfiguration defines availability and partition settings for
// the rollout granularity where it is configured.
type RollingUpdateConfigurationApplyConfiguration struct {
	// MaxUnavailable is the maximum number of resources that may be
	// unavailable during an update. It can be an absolute number (for example,
	// 5) or a percentage (for example, 10%). A percentage is calculated from
	// ModelServing replicas for ServingGroupRollingUpdate and from the
	// corresponding Role's replicas for RoleRollingUpdate, then rounded down.
	// It may resolve to 0 only when MaxSurge resolves above 0. Defaults to 1.
	MaxUnavailable *intstr.IntOrString `json:"maxUnavailable,omitempty"`
	// MaxSurge is the maximum number of resources that may be created above
	// the desired replica count during an update. It can be an absolute number
	// (for example, 1) or a percentage (for example, 25%). A percentage is
	// calculated from ModelServing replicas for ServingGroupRollingUpdate and
	// from the corresponding Role's replicas for RoleRollingUpdate, then rounded
	// up. It defaults to 0.
	MaxSurge *intstr.IntOrString `json:"maxSurge,omitempty"`
	// Partition protects the first N existing replicas in ascending ordinal order
	// from updates. The remaining replicas are eligible for rolling update.
	// For a contiguous ordinal set, this is equivalent to protecting [0, Partition).
	// Value can be an absolute number (ex: 5) or a percentage of total replicas (ex: 10%).
	// Absolute number is calculated from percentage by rounding up.
	// The default value is 0.
	Partition *intstr.IntOrString `json:"partition,omitempty"`
}

// RollingUpdateConfigurationApplyConfiguration constructs a declarative configuration of the RollingUpdateConfiguration type for use with
// apply.
func RollingUpdateConfiguration() *RollingUpdateConfigurationApplyConfiguration {
	return &RollingUpdateConfigurationApplyConfiguration{}
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *RollingUpdateConfigurationApplyConfiguration) WithMaxUnavailable(value intstr.IntOrString) *RollingUpdateConfigurationApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}

// WithMaxSurge sets the MaxSurge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSurge field is set to the value of the last call.
func (b *RollingUpdateConfigurationApplyConfiguration) WithMaxSurge(value intstr.IntOrString) *RollingUpdateConfigurationApplyConfiguration {
	b.MaxSurge = &value
	return b
}

// WithPartition sets the Partition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Partition field is set to the value of the last call.
func (b *RollingUpdateConfigurationApplyConfiguration) WithPartition(value intstr.IntOrString) *RollingUpdateConfigurationApplyConfiguration {
	b.Partition = &value
	return b
}
