/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// TargetApplyConfiguration represents a declarative configuration of the Target type for use
// with apply.
//
// Target defines a ModelServing deployment that can be monitored and scaled.
//
// Example:
//
// target:
// targetRef:
// kind: ModelServing
// name: podinfo-ms
// metricSources:
// podinfo_rps:
// prometheus:
// serverURL: http://prometheus.monitoring.svc:9090
// query: sum(rate(http_requests_total[2m]))
type TargetApplyConfiguration struct {
	// TargetRef references the target object to be monitored and scaled.
	// Default target GVK is ModelServing. Currently supported kinds: ModelServing.
	// Example: kind=ModelServing, name=podinfo-ms.
	TargetRef *v1.ObjectReference `json:"targetRef,omitempty"`
	// MetricSources declares how to fetch specific metrics for this target.
	// Keys must match AutoscalingPolicy.spec.metrics[].name.
	// Missing keys are treated as missing metrics for that reconcile loop.
	// For example, a key "podinfo_rps" here must correspond to a metric named
	// "podinfo_rps" in the referenced AutoscalingPolicy.
	MetricSources map[string]MetricSourceApplyConfiguration `json:"metricSources,omitempty"`
}

// TargetApplyConfiguration constructs a declarative configuration of the Target type for use with
// apply.
func Target() *TargetApplyConfiguration {
	return &TargetApplyConfiguration{}
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *TargetApplyConfiguration) WithTargetRef(value v1.ObjectReference) *TargetApplyConfiguration {
	b.TargetRef = &value
	return b
}

// WithMetricSources puts the entries into the MetricSources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MetricSources field,
// overwriting an existing map entries in MetricSources field with the same key.
func (b *TargetApplyConfiguration) WithMetricSources(entries map[string]MetricSourceApplyConfiguration) *TargetApplyConfiguration {
	if b.MetricSources == nil && len(entries) > 0 {
		b.MetricSources = make(map[string]MetricSourceApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.MetricSources[k] = v
	}
	return b
}
