/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetScalingStatusApplyConfiguration represents a declarative configuration of the TargetScalingStatus type for use
// with apply.
//
// TargetScalingStatus reports the observed scaling state of a single scalable
// unit (a whole ModelServing, or one role within it).
type TargetScalingStatusApplyConfiguration struct {
	// Name identifies the unit when this status appears in a list.
	// It is required for HeterogeneousStatus entries and DisaggregatedStatus roles,
	// and may be empty for HomogeneousStatus because the target is implied.
	Name *string `json:"name,omitempty"`
	// CurrentReplicas is the number of replicas currently observed.
	CurrentReplicas *int32 `json:"currentReplicas,omitempty"`
	// DesiredReplicas is the number of replicas the controller computed from
	// metrics, before ratio enforcement.
	DesiredReplicas *int32 `json:"desiredReplicas,omitempty"`
	// Mode reports whether the unit is currently in "Stable" or "Panic" mode.
	Mode *string `json:"mode,omitempty"`
	// LastScaleTime is the last time the unit was scaled by the controller.
	LastScaleTime *v1.Time `json:"lastScaleTime,omitempty"`
}

// TargetScalingStatusApplyConfiguration constructs a declarative configuration of the TargetScalingStatus type for use with
// apply.
func TargetScalingStatus() *TargetScalingStatusApplyConfiguration {
	return &TargetScalingStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TargetScalingStatusApplyConfiguration) WithName(value string) *TargetScalingStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithCurrentReplicas sets the CurrentReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentReplicas field is set to the value of the last call.
func (b *TargetScalingStatusApplyConfiguration) WithCurrentReplicas(value int32) *TargetScalingStatusApplyConfiguration {
	b.CurrentReplicas = &value
	return b
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *TargetScalingStatusApplyConfiguration) WithDesiredReplicas(value int32) *TargetScalingStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *TargetScalingStatusApplyConfiguration) WithMode(value string) *TargetScalingStatusApplyConfiguration {
	b.Mode = &value
	return b
}

// WithLastScaleTime sets the LastScaleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScaleTime field is set to the value of the last call.
func (b *TargetScalingStatusApplyConfiguration) WithLastScaleTime(value v1.Time) *TargetScalingStatusApplyConfiguration {
	b.LastScaleTime = &value
	return b
}
