apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"kthena-router"},"name":"kthena-router","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/component":"kthena-router"}}}
  creationTimestamp: "2026-03-24T19:21:59Z"
  labels:
    app.kubernetes.io/component: kthena-router
  name: kthena-router
  namespace: default
  resourceVersion: "15396"
  uid: ec3ae0ee-465f-4829-bf55-8558f7e167cc
spec:
  clusterIP: 10.96.60.116
  clusterIPs:
  - 10.96.60.116
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: kthena-router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
