apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kthena-router
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kthena-system
  selector:
    matchLabels:
      app.kubernetes.io/component: kthena-router-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
