/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationworkloadv1alpha1 "github.com/volcano-sh/kthena/client-go/applyconfiguration/workload/v1alpha1"
	scheme "github.com/volcano-sh/kthena/client-go/clientset/versioned/scheme"
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModelServingRoleReplicasGetter has a method to return a ModelServingRoleReplicaInterface.
// A group's client should implement this interface.
type ModelServingRoleReplicasGetter interface {
	ModelServingRoleReplicas(namespace string) ModelServingRoleReplicaInterface
}

// ModelServingRoleReplicaInterface has methods to work with ModelServingRoleReplica resources.
type ModelServingRoleReplicaInterface interface {
	Create(ctx context.Context, modelServingRoleReplica *workloadv1alpha1.ModelServingRoleReplica, opts v1.CreateOptions) (*workloadv1alpha1.ModelServingRoleReplica, error)
	Update(ctx context.Context, modelServingRoleReplica *workloadv1alpha1.ModelServingRoleReplica, opts v1.UpdateOptions) (*workloadv1alpha1.ModelServingRoleReplica, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelServingRoleReplica *workloadv1alpha1.ModelServingRoleReplica, opts v1.UpdateOptions) (*workloadv1alpha1.ModelServingRoleReplica, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadv1alpha1.ModelServingRoleReplica, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadv1alpha1.ModelServingRoleReplicaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadv1alpha1.ModelServingRoleReplica, err error)
	Apply(ctx context.Context, modelServingRoleReplica *applyconfigurationworkloadv1alpha1.ModelServingRoleReplicaApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.ModelServingRoleReplica, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, modelServingRoleReplica *applyconfigurationworkloadv1alpha1.ModelServingRoleReplicaApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.ModelServingRoleReplica, err error)
	ModelServingRoleReplicaExpansion
}

// modelServingRoleReplicas implements ModelServingRoleReplicaInterface
type modelServingRoleReplicas struct {
	*gentype.ClientWithListAndApply[*workloadv1alpha1.ModelServingRoleReplica, *workloadv1alpha1.ModelServingRoleReplicaList, *applyconfigurationworkloadv1alpha1.ModelServingRoleReplicaApplyConfiguration]
}

// newModelServingRoleReplicas returns a ModelServingRoleReplicas
func newModelServingRoleReplicas(c *WorkloadV1alpha1Client, namespace string) *modelServingRoleReplicas {
	return &modelServingRoleReplicas{
		gentype.NewClientWithListAndApply[*workloadv1alpha1.ModelServingRoleReplica, *workloadv1alpha1.ModelServingRoleReplicaList, *applyconfigurationworkloadv1alpha1.ModelServingRoleReplicaApplyConfiguration](
			"modelservingrolereplicas",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadv1alpha1.ModelServingRoleReplica { return &workloadv1alpha1.ModelServingRoleReplica{} },
			func() *workloadv1alpha1.ModelServingRoleReplicaList {
				return &workloadv1alpha1.ModelServingRoleReplicaList{}
			},
		),
	}
}
