/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ModelServingRoleReplicaLister helps list ModelServingRoleReplicas.
// All objects returned here must be treated as read-only.
type ModelServingRoleReplicaLister interface {
	// List lists all ModelServingRoleReplicas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadv1alpha1.ModelServingRoleReplica, err error)
	// ModelServingRoleReplicas returns an object that can list and get ModelServingRoleReplicas.
	ModelServingRoleReplicas(namespace string) ModelServingRoleReplicaNamespaceLister
	ModelServingRoleReplicaListerExpansion
}

// modelServingRoleReplicaLister implements the ModelServingRoleReplicaLister interface.
type modelServingRoleReplicaLister struct {
	listers.ResourceIndexer[*workloadv1alpha1.ModelServingRoleReplica]
}

// NewModelServingRoleReplicaLister returns a new ModelServingRoleReplicaLister.
func NewModelServingRoleReplicaLister(indexer cache.Indexer) ModelServingRoleReplicaLister {
	return &modelServingRoleReplicaLister{listers.New[*workloadv1alpha1.ModelServingRoleReplica](indexer, workloadv1alpha1.Resource("modelservingrolereplica"))}
}

// ModelServingRoleReplicas returns an object that can list and get ModelServingRoleReplicas.
func (s *modelServingRoleReplicaLister) ModelServingRoleReplicas(namespace string) ModelServingRoleReplicaNamespaceLister {
	return modelServingRoleReplicaNamespaceLister{listers.NewNamespaced[*workloadv1alpha1.ModelServingRoleReplica](s.ResourceIndexer, namespace)}
}

// ModelServingRoleReplicaNamespaceLister helps list and get ModelServingRoleReplicas.
// All objects returned here must be treated as read-only.
type ModelServingRoleReplicaNamespaceLister interface {
	// List lists all ModelServingRoleReplicas in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadv1alpha1.ModelServingRoleReplica, err error)
	// Get retrieves the ModelServingRoleReplica from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadv1alpha1.ModelServingRoleReplica, error)
	ModelServingRoleReplicaNamespaceListerExpansion
}

// modelServingRoleReplicaNamespaceLister implements the ModelServingRoleReplicaNamespaceLister
// interface.
type modelServingRoleReplicaNamespaceLister struct {
	listers.ResourceIndexer[*workloadv1alpha1.ModelServingRoleReplica]
}
