/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BodyMatchApplyConfiguration represents a declarative configuration of the BodyMatch type for use
// with apply.
//
// BodyMatch defines the predicate used to match request body content
type BodyMatchApplyConfiguration struct {
	// Model is the name of the model or lora adapter to match.
	// If this field is not specified, any model or lora adapter will be matched.
	Model *string `json:"model,omitempty"`
}

// BodyMatchApplyConfiguration constructs a declarative configuration of the BodyMatch type for use with
// apply.
func BodyMatch() *BodyMatchApplyConfiguration {
	return &BodyMatchApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *BodyMatchApplyConfiguration) WithModel(value string) *BodyMatchApplyConfiguration {
	b.Model = &value
	return b
}
