/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConnectionPoolApplyConfiguration represents a declarative configuration of the ConnectionPool type for use
// with apply.
//
// ConnectionPool configures the HTTP connection pool for a ModelServer.
type ConnectionPoolApplyConfiguration struct {
	// MaxIdleConnections is the total idle connections across all endpoints.
	// Defaults to 100 when omitted.
	MaxIdleConnections *int32 `json:"maxIdleConnections,omitempty"`
	// MaxIdleConnectionsPerHost is the idle connections per pod/endpoint.
	// Defaults to 64 when omitted.
	MaxIdleConnectionsPerHost *int32 `json:"maxIdleConnectionsPerHost,omitempty"`
	// MaxConnectionsPerHost limits dialing, active and idle connections per host.
	// 0 means unlimited. Defaults to 0 when omitted.
	MaxConnectionsPerHost *int32 `json:"maxConnectionsPerHost,omitempty"`
	// IdleTimeout is how long an idle connection stays open before closing.
	// Defaults to 90s when omitted.
	IdleTimeout *v1.Duration `json:"idleTimeout,omitempty"`
}

// ConnectionPoolApplyConfiguration constructs a declarative configuration of the ConnectionPool type for use with
// apply.
func ConnectionPool() *ConnectionPoolApplyConfiguration {
	return &ConnectionPoolApplyConfiguration{}
}

// WithMaxIdleConnections sets the MaxIdleConnections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxIdleConnections field is set to the value of the last call.
func (b *ConnectionPoolApplyConfiguration) WithMaxIdleConnections(value int32) *ConnectionPoolApplyConfiguration {
	b.MaxIdleConnections = &value
	return b
}

// WithMaxIdleConnectionsPerHost sets the MaxIdleConnectionsPerHost field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxIdleConnectionsPerHost field is set to the value of the last call.
func (b *ConnectionPoolApplyConfiguration) WithMaxIdleConnectionsPerHost(value int32) *ConnectionPoolApplyConfiguration {
	b.MaxIdleConnectionsPerHost = &value
	return b
}

// WithMaxConnectionsPerHost sets the MaxConnectionsPerHost field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConnectionsPerHost field is set to the value of the last call.
func (b *ConnectionPoolApplyConfiguration) WithMaxConnectionsPerHost(value int32) *ConnectionPoolApplyConfiguration {
	b.MaxConnectionsPerHost = &value
	return b
}

// WithIdleTimeout sets the IdleTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IdleTimeout field is set to the value of the last call.
func (b *ConnectionPoolApplyConfiguration) WithIdleTimeout(value v1.Duration) *ConnectionPoolApplyConfiguration {
	b.IdleTimeout = &value
	return b
}
