/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// ExternalProviderApplyConfiguration represents a declarative configuration of the ExternalProvider type for use
// with apply.
type ExternalProviderApplyConfiguration struct {
	ProviderType   *networkingv1alpha1.ExternalProviderType `json:"providerType,omitempty"`
	Endpoint       *string                                  `json:"endpoint,omitempty"`
	CredentialsRef *v1.LocalObjectReference                 `json:"credentialsRef,omitempty"`
}

// ExternalProviderApplyConfiguration constructs a declarative configuration of the ExternalProvider type for use with
// apply.
func ExternalProvider() *ExternalProviderApplyConfiguration {
	return &ExternalProviderApplyConfiguration{}
}

// WithProviderType sets the ProviderType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderType field is set to the value of the last call.
func (b *ExternalProviderApplyConfiguration) WithProviderType(value networkingv1alpha1.ExternalProviderType) *ExternalProviderApplyConfiguration {
	b.ProviderType = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *ExternalProviderApplyConfiguration) WithEndpoint(value string) *ExternalProviderApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithCredentialsRef sets the CredentialsRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsRef field is set to the value of the last call.
func (b *ExternalProviderApplyConfiguration) WithCredentialsRef(value v1.LocalObjectReference) *ExternalProviderApplyConfiguration {
	b.CredentialsRef = &value
	return b
}
