/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
)

// ExternalModelProviderSpecApplyConfiguration represents a declarative configuration of the ExternalModelProviderSpec type for use
// with apply.
type ExternalModelProviderSpecApplyConfiguration struct {
	ProviderType       *networkingv1alpha1.ExternalProviderType `json:"providerType,omitempty"`
	Model              *string                                  `json:"model,omitempty"`
	BaseURL            *string                                  `json:"baseURL,omitempty"`
	InsecureSkipVerify *bool                                    `json:"insecureSkipVerify,omitempty"`
	Auth               *ProviderAuthApplyConfiguration          `json:"auth,omitempty"`
	Headers            map[string]string                        `json:"headers,omitempty"`
}

// ExternalModelProviderSpecApplyConfiguration constructs a declarative configuration of the ExternalModelProviderSpec type for use with
// apply.
func ExternalModelProviderSpec() *ExternalModelProviderSpecApplyConfiguration {
	return &ExternalModelProviderSpecApplyConfiguration{}
}

// WithProviderType sets the ProviderType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderType field is set to the value of the last call.
func (b *ExternalModelProviderSpecApplyConfiguration) WithProviderType(value networkingv1alpha1.ExternalProviderType) *ExternalModelProviderSpecApplyConfiguration {
	b.ProviderType = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *ExternalModelProviderSpecApplyConfiguration) WithModel(value string) *ExternalModelProviderSpecApplyConfiguration {
	b.Model = &value
	return b
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *ExternalModelProviderSpecApplyConfiguration) WithBaseURL(value string) *ExternalModelProviderSpecApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithInsecureSkipVerify sets the InsecureSkipVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureSkipVerify field is set to the value of the last call.
func (b *ExternalModelProviderSpecApplyConfiguration) WithInsecureSkipVerify(value bool) *ExternalModelProviderSpecApplyConfiguration {
	b.InsecureSkipVerify = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *ExternalModelProviderSpecApplyConfiguration) WithAuth(value *ProviderAuthApplyConfiguration) *ExternalModelProviderSpecApplyConfiguration {
	b.Auth = value
	return b
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *ExternalModelProviderSpecApplyConfiguration) WithHeaders(entries map[string]string) *ExternalModelProviderSpecApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}
