/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// ModelServerSpecApplyConfiguration represents a declarative configuration of the ModelServerSpec type for use
// with apply.
//
// ModelServerSpec defines the desired state of ModelServer.
type ModelServerSpecApplyConfiguration struct {
	// The real model that the modelServers are running.
	// If the `model` in LLM inference request is different from this field, it should be overwritten by this field.
	// Otherwise, the `model` in LLM inference request will not be mutated.
	Model *string `json:"model,omitempty"`
	// The inference engine used to serve the model.
	InferenceEngine *networkingv1alpha1.InferenceEngine `json:"inferenceEngine,omitempty"`
	// WorkloadSelector is used to match the model serving instances.
	// Currently, they must be pods within the same namespace as modelServer object.
	// `workloadSelector.matchLabels` and `endpoints` are mutually exclusive ways of
	// declaring the serving instances, so exactly one of them must be used.
	// `workloadSelector.pdGroup` does not select instances; it only assigns them
	// prefill and decode roles, and therefore is the sole `workloadSelector` field
	// that may also be combined with `endpoints`.
	WorkloadSelector *WorkloadSelectorApplyConfiguration `json:"workloadSelector,omitempty"`
	// Endpoints is a static list of model serving instances. It is intended for
	// deployments where the serving instances are not discoverable as pods of the
	// cluster the router runs in, for example when the router reads its
	// configuration from local files instead of the Kubernetes API server.
	// `endpoints` and `workloadSelector.matchLabels` are mutually exclusive;
	// exactly one of them must be specified.
	Endpoints []EndpointApplyConfiguration `json:"endpoints,omitempty"`
	// WorkloadPort defines the port and protocol configuration for the model server.
	// It may be omitted only when every entry in `endpoints` declares its own
	// `port`; endpoints without an explicit `port` fall back to `workloadPort.port`.
	WorkloadPort *WorkloadPortApplyConfiguration `json:"workloadPort,omitempty"`
	// Traffic Policy for accessing the model server instance.
	TrafficPolicy *TrafficPolicyApplyConfiguration `json:"trafficPolicy,omitempty"`
	// KVConnector specifies the KV connector configuration for PD disaggregated routing
	KVConnector *KVConnectorSpecApplyConfiguration `json:"kvConnector,omitempty"`
	// APIKeySecretRef references the API key the serving instances require, for
	// example a vLLM engine started with --api-key. The router sends it as a bearer
	// token when discovering the models a pod serves. The Secret must live in this
	// ModelServer's namespace and carry the
	// networking.serving.volcano.sh/external-model-provider-credential label.
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty"`
}

// ModelServerSpecApplyConfiguration constructs a declarative configuration of the ModelServerSpec type for use with
// apply.
func ModelServerSpec() *ModelServerSpecApplyConfiguration {
	return &ModelServerSpecApplyConfiguration{}
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithModel(value string) *ModelServerSpecApplyConfiguration {
	b.Model = &value
	return b
}

// WithInferenceEngine sets the InferenceEngine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InferenceEngine field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithInferenceEngine(value networkingv1alpha1.InferenceEngine) *ModelServerSpecApplyConfiguration {
	b.InferenceEngine = &value
	return b
}

// WithWorkloadSelector sets the WorkloadSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadSelector field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithWorkloadSelector(value *WorkloadSelectorApplyConfiguration) *ModelServerSpecApplyConfiguration {
	b.WorkloadSelector = value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *ModelServerSpecApplyConfiguration) WithEndpoints(values ...*EndpointApplyConfiguration) *ModelServerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}

// WithWorkloadPort sets the WorkloadPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadPort field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithWorkloadPort(value *WorkloadPortApplyConfiguration) *ModelServerSpecApplyConfiguration {
	b.WorkloadPort = value
	return b
}

// WithTrafficPolicy sets the TrafficPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrafficPolicy field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithTrafficPolicy(value *TrafficPolicyApplyConfiguration) *ModelServerSpecApplyConfiguration {
	b.TrafficPolicy = value
	return b
}

// WithKVConnector sets the KVConnector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KVConnector field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithKVConnector(value *KVConnectorSpecApplyConfiguration) *ModelServerSpecApplyConfiguration {
	b.KVConnector = value
	return b
}

// WithAPIKeySecretRef sets the APIKeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIKeySecretRef field is set to the value of the last call.
func (b *ModelServerSpecApplyConfiguration) WithAPIKeySecretRef(value v1.SecretKeySelector) *ModelServerSpecApplyConfiguration {
	b.APIKeySecretRef = &value
	return b
}
