/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ModelServerStatusApplyConfiguration represents a declarative configuration of the ModelServerStatus type for use
// with apply.
type ModelServerStatusApplyConfiguration struct {
	ObservedGeneration *int64                           `json:"observedGeneration,omitempty"`
	ReadyReplicas      *int32                           `json:"readyReplicas,omitempty"`
	MatchedReplicas    *int32                           `json:"matchedReplicas,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ModelServerStatusApplyConfiguration constructs a declarative configuration of the ModelServerStatus type for use with
// apply.
func ModelServerStatus() *ModelServerStatusApplyConfiguration {
	return &ModelServerStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ModelServerStatusApplyConfiguration) WithObservedGeneration(value int64) *ModelServerStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ModelServerStatusApplyConfiguration) WithReadyReplicas(value int32) *ModelServerStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithMatchedReplicas sets the MatchedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchedReplicas field is set to the value of the last call.
func (b *ModelServerStatusApplyConfiguration) WithMatchedReplicas(value int32) *ModelServerStatusApplyConfiguration {
	b.MatchedReplicas = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ModelServerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ModelServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
