/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
)

// RateLimitApplyConfiguration represents a declarative configuration of the RateLimit type for use
// with apply.
type RateLimitApplyConfiguration struct {
	// InputTokensPerUnit is the maximum number of input tokens allowed per unit of time.
	// If this field is not set, there is no limit on input tokens.
	InputTokensPerUnit *uint32 `json:"inputTokensPerUnit,omitempty"`
	// OutputTokensPerUnit is the maximum number of output tokens allowed per unit of time.
	// If this field is not set, there is no limit on output tokens.
	OutputTokensPerUnit *uint32 `json:"outputTokensPerUnit,omitempty"`
	// Unit is the time unit for the rate limit.
	Unit *networkingv1alpha1.RateLimitUnit `json:"unit,omitempty"`
	// Global contains configuration for global rate limiting using distributed storage.
	// If this field is set, global rate limiting will be used; otherwise, local rate limiting will be used.
	Global *GlobalRateLimitApplyConfiguration `json:"global,omitempty"`
}

// RateLimitApplyConfiguration constructs a declarative configuration of the RateLimit type for use with
// apply.
func RateLimit() *RateLimitApplyConfiguration {
	return &RateLimitApplyConfiguration{}
}

// WithInputTokensPerUnit sets the InputTokensPerUnit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InputTokensPerUnit field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithInputTokensPerUnit(value uint32) *RateLimitApplyConfiguration {
	b.InputTokensPerUnit = &value
	return b
}

// WithOutputTokensPerUnit sets the OutputTokensPerUnit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutputTokensPerUnit field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithOutputTokensPerUnit(value uint32) *RateLimitApplyConfiguration {
	b.OutputTokensPerUnit = &value
	return b
}

// WithUnit sets the Unit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unit field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithUnit(value networkingv1alpha1.RateLimitUnit) *RateLimitApplyConfiguration {
	b.Unit = &value
	return b
}

// WithGlobal sets the Global field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Global field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithGlobal(value *GlobalRateLimitApplyConfiguration) *RateLimitApplyConfiguration {
	b.Global = value
	return b
}
