/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RetryApplyConfiguration represents a declarative configuration of the Retry type for use
// with apply.
type RetryApplyConfiguration struct {
	// The maximum number of times an individual inference request to a model server should be retried.
	// If the maximum number of retries has been done without a successgful response, the request will be considered failed.
	Attempts *int32 `json:"attempts,omitempty"`
	// RetryInterval is the interval between retries.
	RetryInterval *v1.Duration `json:"retryInterval,omitempty"`
}

// RetryApplyConfiguration constructs a declarative configuration of the Retry type for use with
// apply.
func Retry() *RetryApplyConfiguration {
	return &RetryApplyConfiguration{}
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *RetryApplyConfiguration) WithAttempts(value int32) *RetryApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithRetryInterval sets the RetryInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryInterval field is set to the value of the last call.
func (b *RetryApplyConfiguration) WithRetryInterval(value v1.Duration) *RetryApplyConfiguration {
	b.RetryInterval = &value
	return b
}
