/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
)

// RuleApplyConfiguration represents a declarative configuration of the Rule type for use
// with apply.
type RuleApplyConfiguration struct {
	// Name is the name of the rule.
	Name *string `json:"name,omitempty"`
	// Match conditions to be satisfied for the rule to be activated.
	// Empty `modelMatch` means matching all requests.
	ModelMatch   *ModelMatchApplyConfiguration     `json:"modelMatch,omitempty"`
	TargetModels []*networkingv1alpha1.TargetModel `json:"targetModels,omitempty"`
}

// RuleApplyConfiguration constructs a declarative configuration of the Rule type for use with
// apply.
func Rule() *RuleApplyConfiguration {
	return &RuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RuleApplyConfiguration) WithName(value string) *RuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithModelMatch sets the ModelMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelMatch field is set to the value of the last call.
func (b *RuleApplyConfiguration) WithModelMatch(value *ModelMatchApplyConfiguration) *RuleApplyConfiguration {
	b.ModelMatch = value
	return b
}

// WithTargetModels adds the given value to the TargetModels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetModels field.
func (b *RuleApplyConfiguration) WithTargetModels(values ...**networkingv1alpha1.TargetModel) *RuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetModels")
		}
		b.TargetModels = append(b.TargetModels, *values[i])
	}
	return b
}
