/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SessionStickyApplyConfiguration represents a declarative configuration of the SessionSticky type for use
// with apply.
type SessionStickyApplyConfiguration struct {
	SessionAffinitySeconds *int32                               `json:"sessionAffinitySeconds,omitempty"`
	Sources                []SessionKeySourceApplyConfiguration `json:"sources,omitempty"`
}

// SessionStickyApplyConfiguration constructs a declarative configuration of the SessionSticky type for use with
// apply.
func SessionSticky() *SessionStickyApplyConfiguration {
	return &SessionStickyApplyConfiguration{}
}

// WithSessionAffinitySeconds sets the SessionAffinitySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionAffinitySeconds field is set to the value of the last call.
func (b *SessionStickyApplyConfiguration) WithSessionAffinitySeconds(value int32) *SessionStickyApplyConfiguration {
	b.SessionAffinitySeconds = &value
	return b
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *SessionStickyApplyConfiguration) WithSources(values ...*SessionKeySourceApplyConfiguration) *SessionStickyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSources")
		}
		b.Sources = append(b.Sources, *values[i])
	}
	return b
}
