/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// StringMatchApplyConfiguration represents a declarative configuration of the StringMatch type for use
// with apply.
//
// StringMatch defines the matching conditions for string fields.
// Only one of the fields may be set.
type StringMatchApplyConfiguration struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	Regex  *string `json:"regex,omitempty"`
}

// StringMatchApplyConfiguration constructs a declarative configuration of the StringMatch type for use with
// apply.
func StringMatch() *StringMatchApplyConfiguration {
	return &StringMatchApplyConfiguration{}
}

// WithExact sets the Exact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exact field is set to the value of the last call.
func (b *StringMatchApplyConfiguration) WithExact(value string) *StringMatchApplyConfiguration {
	b.Exact = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *StringMatchApplyConfiguration) WithPrefix(value string) *StringMatchApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *StringMatchApplyConfiguration) WithRegex(value string) *StringMatchApplyConfiguration {
	b.Regex = &value
	return b
}
