/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TargetModelApplyConfiguration represents a declarative configuration of the TargetModel type for use
// with apply.
type TargetModelApplyConfiguration struct {
	ModelServerName           *string `json:"modelServerName,omitempty"`
	ExternalModelProviderName *string `json:"externalModelProviderName,omitempty"`
	Weight                    *uint32 `json:"weight,omitempty"`
}

// TargetModelApplyConfiguration constructs a declarative configuration of the TargetModel type for use with
// apply.
func TargetModel() *TargetModelApplyConfiguration {
	return &TargetModelApplyConfiguration{}
}

// WithModelServerName sets the ModelServerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelServerName field is set to the value of the last call.
func (b *TargetModelApplyConfiguration) WithModelServerName(value string) *TargetModelApplyConfiguration {
	b.ModelServerName = &value
	return b
}

// WithExternalModelProviderName sets the ExternalModelProviderName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalModelProviderName field is set to the value of the last call.
func (b *TargetModelApplyConfiguration) WithExternalModelProviderName(value string) *TargetModelApplyConfiguration {
	b.ExternalModelProviderName = &value
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *TargetModelApplyConfiguration) WithWeight(value uint32) *TargetModelApplyConfiguration {
	b.Weight = &value
	return b
}
