/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrafficPolicyApplyConfiguration represents a declarative configuration of the TrafficPolicy type for use
// with apply.
type TrafficPolicyApplyConfiguration struct {
	Timeout        *v1.Duration                      `json:"timeout,omitempty"`
	Retry          *RetryApplyConfiguration          `json:"retry,omitempty"`
	ConnectionPool *ConnectionPoolApplyConfiguration `json:"connectionPool,omitempty"`
	SessionSticky  *SessionStickyApplyConfiguration  `json:"sessionSticky,omitempty"`
}

// TrafficPolicyApplyConfiguration constructs a declarative configuration of the TrafficPolicy type for use with
// apply.
func TrafficPolicy() *TrafficPolicyApplyConfiguration {
	return &TrafficPolicyApplyConfiguration{}
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *TrafficPolicyApplyConfiguration) WithTimeout(value v1.Duration) *TrafficPolicyApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *TrafficPolicyApplyConfiguration) WithRetry(value *RetryApplyConfiguration) *TrafficPolicyApplyConfiguration {
	b.Retry = value
	return b
}

// WithConnectionPool sets the ConnectionPool field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionPool field is set to the value of the last call.
func (b *TrafficPolicyApplyConfiguration) WithConnectionPool(value *ConnectionPoolApplyConfiguration) *TrafficPolicyApplyConfiguration {
	b.ConnectionPool = value
	return b
}

// WithSessionSticky sets the SessionSticky field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionSticky field is set to the value of the last call.
func (b *TrafficPolicyApplyConfiguration) WithSessionSticky(value *SessionStickyApplyConfiguration) *TrafficPolicyApplyConfiguration {
	b.SessionSticky = value
	return b
}
