/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// WorkloadPortApplyConfiguration represents a declarative configuration of the WorkloadPort type for use
// with apply.
//
// WorkloadPort defines the port and protocol configuration for the model server.
type WorkloadPortApplyConfiguration struct {
	// The port of the model server. The number must be between 1 and 65535.
	Port *int32 `json:"port,omitempty"`
	// The protocol of the model server. Supported values are "http" and "https".
	Protocol *string `json:"protocol,omitempty"`
}

// WorkloadPortApplyConfiguration constructs a declarative configuration of the WorkloadPort type for use with
// apply.
func WorkloadPort() *WorkloadPortApplyConfiguration {
	return &WorkloadPortApplyConfiguration{}
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *WorkloadPortApplyConfiguration) WithPort(value int32) *WorkloadPortApplyConfiguration {
	b.Port = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *WorkloadPortApplyConfiguration) WithProtocol(value string) *WorkloadPortApplyConfiguration {
	b.Protocol = &value
	return b
}
