/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// WorkloadSelectorApplyConfiguration represents a declarative configuration of the WorkloadSelector type for use
// with apply.
//
// WorkloadSelector is used to match the model serving instances.
// Currently, they must be pods within the same namespace as modelServer object.
type WorkloadSelectorApplyConfiguration struct {
	// The base labels to match the model serving instances.
	// All serving instances must match these labels.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
	// PDGroup is used to further match different roles of the model serving instances,
	// mainly used in case like PD disaggregation.
	PDGroup *PDGroupApplyConfiguration `json:"pdGroup,omitempty"`
}

// WorkloadSelectorApplyConfiguration constructs a declarative configuration of the WorkloadSelector type for use with
// apply.
func WorkloadSelector() *WorkloadSelectorApplyConfiguration {
	return &WorkloadSelectorApplyConfiguration{}
}

// WithMatchLabels puts the entries into the MatchLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MatchLabels field,
// overwriting an existing map entries in MatchLabels field with the same key.
func (b *WorkloadSelectorApplyConfiguration) WithMatchLabels(entries map[string]string) *WorkloadSelectorApplyConfiguration {
	if b.MatchLabels == nil && len(entries) > 0 {
		b.MatchLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.MatchLabels[k] = v
	}
	return b
}

// WithPDGroup sets the PDGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PDGroup field is set to the value of the last call.
func (b *WorkloadSelectorApplyConfiguration) WithPDGroup(value *PDGroupApplyConfiguration) *WorkloadSelectorApplyConfiguration {
	b.PDGroup = value
	return b
}
