apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../model-serving/prefill-decode-disaggregation
  - ModelServer-prefill-decode-disaggregation.yaml
  - ModelRoute-prefill-decode-disaggregation.yaml
