/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationnetworkingv1alpha1 "github.com/volcano-sh/kthena/client-go/applyconfiguration/networking/v1alpha1"
	scheme "github.com/volcano-sh/kthena/client-go/clientset/versioned/scheme"
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ExternalModelProvidersGetter has a method to return a ExternalModelProviderInterface.
// A group's client should implement this interface.
type ExternalModelProvidersGetter interface {
	ExternalModelProviders(namespace string) ExternalModelProviderInterface
}

// ExternalModelProviderInterface has methods to work with ExternalModelProvider resources.
type ExternalModelProviderInterface interface {
	Create(ctx context.Context, externalModelProvider *networkingv1alpha1.ExternalModelProvider, opts v1.CreateOptions) (*networkingv1alpha1.ExternalModelProvider, error)
	Update(ctx context.Context, externalModelProvider *networkingv1alpha1.ExternalModelProvider, opts v1.UpdateOptions) (*networkingv1alpha1.ExternalModelProvider, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, externalModelProvider *networkingv1alpha1.ExternalModelProvider, opts v1.UpdateOptions) (*networkingv1alpha1.ExternalModelProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkingv1alpha1.ExternalModelProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkingv1alpha1.ExternalModelProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkingv1alpha1.ExternalModelProvider, err error)
	Apply(ctx context.Context, externalModelProvider *applyconfigurationnetworkingv1alpha1.ExternalModelProviderApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha1.ExternalModelProvider, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, externalModelProvider *applyconfigurationnetworkingv1alpha1.ExternalModelProviderApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha1.ExternalModelProvider, err error)
	ExternalModelProviderExpansion
}

// externalModelProviders implements ExternalModelProviderInterface
type externalModelProviders struct {
	*gentype.ClientWithListAndApply[*networkingv1alpha1.ExternalModelProvider, *networkingv1alpha1.ExternalModelProviderList, *applyconfigurationnetworkingv1alpha1.ExternalModelProviderApplyConfiguration]
}

// newExternalModelProviders returns a ExternalModelProviders
func newExternalModelProviders(c *NetworkingV1alpha1Client, namespace string) *externalModelProviders {
	return &externalModelProviders{
		gentype.NewClientWithListAndApply[*networkingv1alpha1.ExternalModelProvider, *networkingv1alpha1.ExternalModelProviderList, *applyconfigurationnetworkingv1alpha1.ExternalModelProviderApplyConfiguration](
			"externalmodelproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkingv1alpha1.ExternalModelProvider { return &networkingv1alpha1.ExternalModelProvider{} },
			func() *networkingv1alpha1.ExternalModelProviderList {
				return &networkingv1alpha1.ExternalModelProviderList{}
			},
		),
	}
}
