# Authorized and unauthorized licenses in LOWER CASE
[Licenses]
authorized_licenses:
        bsd
        new bsd
        bsd license
        bsd-3-clause
        new bsd license
        simplified bsd
        apache
        apache 2.0
        apache-2.0
        apache software license
        apache software
        gnu lgpl
        lgpl with exceptions or zpl
        isc license
        isc license (iscl)
        mpl 2.0
        mpl-2.0
        mpl-2.0 and mit
        mozilla public license 2.0 (mpl 2.0)
        bsd-2-clause
        bsd 2-clause
        mit
        mit license
        python software foundation
        python software foundation license
        zpl 2.1
        unlicense
        the unlicense
        the unlicense (unlicense)
        psf-2.0

unauthorized_licenses:
        gpl v3
        gpl-3.0
        lgpl-2.0

[Authorized Packages]
setuptools: >=0.0.0
