# Kthena ModelServer
apiVersion: networking.serving.volcano.sh/v1alpha1
kind: ModelServer
metadata:
  name: mocker-model-server
  namespace: default
  labels:
    app: mocker-model-server
spec:
  model: "Qwen/Qwen3-0.6B"
  inferenceEngine: SGLang
  workloadSelector:
    matchLabels:
      app: mocker-llm
  workloadPort:
    port: 30000
    protocol: http
