/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "github.com/volcano-sh/kthena/client-go/clientset/versioned"
	internalinterfaces "github.com/volcano-sh/kthena/client-go/informers/externalversions/internalinterfaces"
	workloadv1alpha1 "github.com/volcano-sh/kthena/client-go/listers/workload/v1alpha1"
	apisworkloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ModelServingRoleReplicaInformer provides access to a shared informer and lister for
// ModelServingRoleReplicas.
type ModelServingRoleReplicaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() workloadv1alpha1.ModelServingRoleReplicaLister
}

type modelServingRoleReplicaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewModelServingRoleReplicaInformer constructs a new informer for ModelServingRoleReplica type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewModelServingRoleReplicaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredModelServingRoleReplicaInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredModelServingRoleReplicaInformer constructs a new informer for ModelServingRoleReplica type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredModelServingRoleReplicaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadV1alpha1().ModelServingRoleReplicas(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadV1alpha1().ModelServingRoleReplicas(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadV1alpha1().ModelServingRoleReplicas(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkloadV1alpha1().ModelServingRoleReplicas(namespace).Watch(ctx, options)
			},
		},
		&apisworkloadv1alpha1.ModelServingRoleReplica{},
		resyncPeriod,
		indexers,
	)
}

func (f *modelServingRoleReplicaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredModelServingRoleReplicaInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *modelServingRoleReplicaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisworkloadv1alpha1.ModelServingRoleReplica{}, f.defaultInformer)
}

func (f *modelServingRoleReplicaInformer) Lister() workloadv1alpha1.ModelServingRoleReplicaLister {
	return workloadv1alpha1.NewModelServingRoleReplicaLister(f.Informer().GetIndexer())
}
