apiVersion: networking.serving.volcano.sh/v1alpha1
kind: ModelServer
metadata:
  name: sglang-mock
  namespace: default
spec:
  workloadSelector:
    matchLabels:
      app: sglang-mock
  workloadPort:
    port: 30000
  model: "meta-llama/Llama-3.1-8B-Instruct"
  inferenceEngine: "SGLang"
  trafficPolicy:
    timeout: 10s
