{{- if .Values.kthenaRouter.sessionSticky.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: kthena-router-session-sticky-redis-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kthena-router
    {{- include "kthena.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.kthenaRouter.sessionSticky.redis.password | b64enc | quote }}
{{- end }}
