apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/version: 6.12.0
    release: kube-prometheus-stack
  name: podinfo
  namespace: autoscale-demo
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - autoscale-demo
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
