name: Documentation Test

on:
  pull_request:
    branches:
      - main
      - "release-*"
permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    name: Check Documentation related changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Check Documentation related changes
        id: filter
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v4
        with:
          filters: |
            docs:
              - "docs/kthena/**"
              - ".github/workflows/docs-tests.yml"

      - name: Skip Documentation tests
        if: steps.filter.outputs.docs != 'true'
        run: echo "No documentation-related files changed; marking required check as passed."

  docs_test:
    name: Docusaurus tests
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.5.0"
          cache: "npm"
          cache-dependency-path: "./docs/kthena/package-lock.json"
      - name: Install dependencies
        working-directory: ./docs/kthena
        run: npm ci
      - name: Run documentation tests
        run: make test-docs
